### ISSUE TITLE
Genesis block hash doesn't match with parity

### ISSUE THREAD

**Issue by ghost** [goerli/go-ethereum-aura#32] opened 2018-09-14 03:33 UTC
Geth dump

```
> eth.getBlock(0)
{
  difficulty: 131072,
  extraData: "0x",
  gasLimit: 6000000,
  gasUsed: 0,
  hash: "0xe1193afff14229ad9b7c3fa3a77cdb81477fcc8119464daec08c7a0066a5bb10",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 0,
  parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 507,
  stateRoot: "0xcef9491631fe6845df55ad70fd7547e26488374fedbfc31a668992fc113bbb62",
  timestamp: 0,
  totalDifficulty: 131072,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
> debug.dumpBlock("latest")
{
  accounts: {
    0000000000000000000000000000000000000001: {
      balance: "1",
      code: "",
      codeHash: "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
      nonce: 0,
      root: "56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      storage: {}
    },
    0000000000000000000000000000000000000002: {
      balance: "1",
      code: "",
      codeHash: "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
      nonce: 0,
      root: "56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      storage: {}
    },
    0000000000000000000000000000000000000003: {
      balance: "1",
      code: "",
      codeHash: "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
      nonce: 0,
      root: "56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      storage: {}
    },
    0000000000000000000000000000000000000004: {
      balance: "1",
      code: "",
      codeHash: "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
      nonce: 0,
      root: "56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      storage: {}
    },
    0015c90d0e12186bc51c9d51aff4d3fb6e984291: {
      balance: "1606938044258990275541962092341162602522202993782792835301376",
      code: "",
      codeHash: "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
      nonce: 0,
      root: "56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      storage: {}
    },
    009fcc115ad9ef38288a82a014dea30f63a84383: {
      balance: "1606938044258990275541962092341162602522202993782792835301376",
      code: "",
      codeHash: "c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
      nonce: 0,
      root: "56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
      storage: {}
    }
  },
  root: "cef9491631fe6845df55ad70fd7547e26488374fedbfc31a668992fc113bbb62"
}
```

Parity dump
```
> eth.getBlock(0)
{
  author: "0x0000000000000000000000000000000000000000",
  difficulty: 131072,
  extraData: "0x",
  gasLimit: 6000000,
  gasUsed: 0,
  hash: "0x4a982649dec9992d0c83d195a81670bfcbe769436a900bab113371a25d7ad4ab",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  number: 0,
  parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sealFields: ["0x80", "0xb841000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ac1dc0ffee"],
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  signature: "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ac1dc0ffee",
  size: 533,
  stateRoot: "0xcef9491631fe6845df55ad70fd7547e26488374fedbfc31a668992fc113bbb62",
  step: "0",
  timestamp: 0,
  totalDifficulty: 131072,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}
```

**Comment by trustfarm-dev** [comment] 2018-09-14 07:17
geth vs parity diff points.

1. hash is different
geth `hash: "0xe1193afff14229ad9b7c3fa3a77cdb81477fcc8119464daec08c7a0066a5bb10",`
parity `hash: "0x4a982649dec9992d0c83d195a81670bfcbe769436a900bab113371a25d7ad4ab",`

2. mixhash missing in parity or redundant added in geth
geth `mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",`

3. signature missing in geth , it makes total size differ
geth ``
parity `  signature: "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ac1dc0ffee",`

4. seal fields missing in geth, it makes total size differ
geth ``
parity `sealFields: ["0x80", "0xb841000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ac1dc0ffee"],`

5. step fileds missing in geth
geth ``
parity `step: "0",`

6. nonce missing in parity
geth `nonce: "0x0000000000000000",`
parity ``

7. THUS size is differ
geth `size: 507,` 
parity `size: 533`

**Comment by 5chdn** [comment] 2018-09-14 09:02
Duplicate of #31

**Closed as completed by 5chdn** 2018-09-14 09:02 UTC
Labels: M2-config 📂, Z7-duplicate 🖨
